export class AppError extends Error {
  constructor(code, message, status = 400, detail) {
    super(message);
    this.name = "AppError";
    this.code = code;
    this.status = status;
    this.detail = detail;
  }
}

export function asAppError(error) {
  if (error instanceof AppError) return error;
  const code = typeof error?.code === "string" ? error.code : "INTERNAL_ERROR";
  const knownStatus = {
    ALGORITHM_EXISTS: 409,
    ALGORITHM_FILENAME_INVALID: 400,
    ALGORITHM_SOURCE_INVALID: 422,
    ALGORITHM_VALIDATION_ERROR: 422,
    ALGORITHM_INVALID: 422,
    ALGORITHM_TOO_LARGE: 413,
    ALGORITHM_FORBIDDEN_CAPABILITY: 422,
    ALGORITHM_WORKER_REQUIRED: 503,
    ENGINE_TIMEOUT: 408,
    ENGINE_ABORTED: 409,
    RESEARCH_PLAN_JSON_INVALID: 400,
    RESEARCH_PLAN_INVALID: 422,
    RESEARCH_PLAN_TOO_LARGE: 413,
    RESEARCH_PLAN_NOT_FOUND: 404,
    RESEARCH_PLAN_VERSION_NOT_FOUND: 404,
    RESEARCH_PLAN_VERSION_MISMATCH: 422,
    RESEARCH_RUN_NOT_FOUND: 404,
    RESEARCH_SNAPSHOT_NOT_FOUND: 404,
    RESEARCH_RUN_CAPACITY: 429,
    RESEARCH_RUN_TOO_LARGE: 413,
    ERR_RESEARCH_RUN_NOT_FOUND: 404,
    ERR_RESEARCH_PLAN_CONFLICT: 409,
    ERR_RESEARCH_PLAN_VERSION_CONFLICT: 409,
    ERR_RESEARCH_RUN_CONFLICT: 409,
    ERR_RESEARCH_RUN_STATE: 409,
    ERR_RESEARCH_SNAPSHOT_CONFLICT: 409,
    ERR_RESEARCH_SNAPSHOT_SCOPE: 422,
    RESEARCH_SYMBOL_INVALID: 422,
    RESEARCH_SYMBOL_NOT_ALLOWED: 422,
    RESEARCH_ADAPTER_NOT_FOUND: 422,
    RESEARCH_ADAPTER_DUPLICATE: 409,
    RESEARCH_TEMPLATE_INVALID: 422,
    RESEARCH_SOURCE_NOT_CONFIGURED: 503,
    RESEARCH_SOURCE_DNS_EMPTY: 502,
    RESEARCH_SOURCE_PRIVATE_ADDRESS: 422,
    RESEARCH_SOURCE_PATH_INVALID: 422,
    RESEARCH_SOURCE_ORIGIN_ESCAPE: 422,
    RESEARCH_SOURCE_REDIRECT_BLOCKED: 422,
    RESEARCH_SOURCE_REDIRECT_LIMIT: 502,
    RESEARCH_SOURCE_HTTP: 502,
    RESEARCH_SOURCE_TIMEOUT: 504,
    RESEARCH_SOURCE_TOO_LARGE: 413,
    RESEARCH_SOURCE_CONTENT_TYPE: 415,
    RESEARCH_SOURCE_ENCODING: 415,
    RESEARCH_SOURCE_JSON_INVALID: 422,
    RESEARCH_SOURCE_EMPTY: 422,
    AI_CLI_UNCONFIGURED: 503,
    AI_CLI_INPUT_EMPTY: 422,
    AI_CLI_INPUT_TOO_LARGE: 413,
    AI_CLI_START_FAILED: 502,
    AI_CLI_TIMEOUT: 504,
    AI_CLI_EXIT_FAILED: 502,
    AI_CLI_OUTPUT_TOO_LARGE: 413,
    AI_CLI_OUTPUT_INVALID: 502,
    RESEARCH_OUTPUT_MISSING: 502,
    RESEARCH_PUBLISH_FAILED: 500,
    RESEARCH_RUN_ABORTED: 409,
    RESEARCH_SOURCE_ABORTED: 409,
    AI_CLI_ABORTED: 409,
    ERR_DATABASE_URL: 500,
    ERR_MIGRATION_DRIFT: 500,
    SQLITE_CONSTRAINT_UNIQUE: 409
  }[code];
  if (knownStatus) return new AppError(code, error instanceof Error ? error.message : code, knownStatus, error?.detail);
  return new AppError("INTERNAL_ERROR", error instanceof Error ? error.message : "Unexpected error", 500);
}

export function unavailable(message, detail) {
  return new AppError("MARKET_DATA_UNAVAILABLE", message, 503, detail);
}
